name: Build Fastest Pekoviewer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    
    - name: Install
      run: |
        pip install PyQt5 Pillow nuitka ordered-set zstandard
    
    - name: Build with Nuitka
      working-directory: src
      shell: cmd
      run: |
        python -m nuitka --msvc=latest --windows-console-mode=disable --standalone --enable-plugin=pyqt5 --lto=yes --assume-yes-for-downloads --output-dir=dist --output-filename=Pekoviewer.exe main.py
    
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: Pekoviewer_Fastest
        path: src/dist/Pekoviewer.dist/
